name: pyjanitor-dev
channels:
  - conda-forge
  - rdkit
dependencies:
  - python>=3.6, <3.9
  - biopython>=1.79
  - black=21.7b0
  - bumpversion>=0.5.3
  - cairo>=1.16.0
  - conda>=4.10.3
  - darglint>=1.8.0
  - doc8>=0.9.0
  - flake8>=3.9.2
  - hypothesis>=4.4.0
  - interrogate>=1.4.0
  - ipykernel>=5.5.5
  - ipython>=7.19.0
  - isort>=5.9.3
  - jupyterlab>=3.1.10
  - lxml>=4.6.3
  - make>=4.3
  - missingno>=0.4.2
  - multipledispatch>=0.6.0
  - mypy>=0.910
  - natsort>=7.1.1
  - nbsphinx>=0.8.7
  - nox>=2021.6.12
  - numpy>=1.21.2
  - openpyxl>=3.0.7
  - pandas-flavor>=0.2.0
  - pandas-vet>=0.2.2
  - pandas>=1.3.2
  - pip>=21.2.4
  - pipreqs>=0.4.10
  - pre-commit>=2.15.0
  - pyflakes>=2.3.1
  - pylint>=2.10.2
  - pyspark>=3.1.2
  - pytest>=6.2.5
  - pytest-cov>=2.12.1
  - pytest-xdist>=2.3.0
  - python-language-server>=0.3.4
  - rdkit>=2021.03.5
  - recommonmark>=0.7.1
  - seaborn>=0.11.2
  - sphinx>=4.1.2
  - sphinxcontrib-fulltoc>=1.2.0
  - twine>= 3.4.2
  - unyt>=2.8.0
  - xarray>=0.19.0
  - xlrd>=2.0.1
  - xorg-libxrender>=0.9.10
